### ISSUE TITLE
Java Script

### ISSUE THREAD

**Issue by RobertElvidge** [RobertElvidge/prework-study-guide#3]
# JavaScript

## User Story
As a boot camp student
I want the prework notes to be structured on a webpage
So that I can easily find and read the information

## Acceptance Criteria
GIVEN a Prework Study Guide website
WHEN I view the study guide
THEN I can see the four topics I learned listed along with a suggestion on what I should study first

**Comment by sohan-gupthak** [comment]
If you are a beginner in programming, it is important to not only focus on reading but also on doing projects and learning from them. When I was learning JavaScript, I worked on basic projects such as creating a to-do list which covered concepts like dynamic appending and local storage, and also creating a Tic Tac Toe game. It is also important to learn about REST APIs and concepts like PUT, GET, POST, and DELETE. 

> W3 Schools is a great resource to learn from:  [https://www.w3schools.com/js/](url).
> can also check out some of my basic projects on my LinkedIn profile:  [https://www.linkedin.com/in/sohan-guptha/](url).
